SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';


-- -----------------------------------------------------
-- Table `Lost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lost` ;

CREATE  TABLE IF NOT EXISTS `Lost` (
  `id` VARCHAR(80) NOT NULL ,
  `user` INT NOT NULL ,
  PRIMARY KEY (`id`) ,
  INDEX `fk_Lost_Users1` (`user` ASC) ,
  CONSTRAINT `fk_Lost_Users1`
    FOREIGN KEY (`user` )
    REFERENCES `Users` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
