<div class="content">
    <h1><?php echo $this->translate('Create category'); ?></h1>
</div>

<div class="content">
    <?php echo $this->form()->openTag($this->form); ?>
    <div>
        <div><?php echo $this->formLabel($this->form->get('title')); ?></div>
        <div><?php echo $this->formElement($this->form->get('title')); ?></div>
        <div><?php echo $this->formElementErrors($this->form->get('title')); ?></div>
    </div>
    <?php echo $this->formHidden($this->form->get('csrf')) . PHP_EOL; ?>
    <?php echo $this->formElementErrors($this->form->get('csrf')) . PHP_EOL; ?>
    <div><?php echo $this->formElement($this->form->get('add')); ?></div>
    <?php echo $this->form()->closeTag($this->form); ?>
</div>