<div class="content">
    <h1><?php echo $this->translate('List of categories'); ?></h1>
</div>

<div class="content" id="categoriesList">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th><?php echo $this->translate('#'); ?></th>
                <th><?php echo $this->translate('Name'); ?></th>
                <th><?php echo $this->translate('Description'); ?></th>
                <th class="action"><?php echo $this->translate('Action'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->data as $k => $row): ?>
            <tr>
                <td><?php echo $k + 1; ?></td>
                <td><?php echo $row->name; ?></td>
                <td><?php echo $row->description; ?></td>
                <td class="action">
                    <a class="btn btn-info" href="<?php echo $this->url('category/edit', array('id' => $row->id)); ?>"><?php echo $this->translate('Edit'); ?></a>
                    <a class="btn btn-danger confirm" rel="delete" href="<?php echo $this->url('category/delete', array('id' => $row->id)); ?>"><?php echo $this->translate('Delete'); ?></a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>