<div id="content" class="content">
    <h1>Money</h1>
    <fieldset>
        <legend>Login to administration</legend>
        <div class="control-group">
            <label class="control-label" for="input01">Email</label>
            <div class="controls">
                <div class="input-append">
                    <input id="email" name="email" type="text" title="Tets info k nejakemu inputu" class="input-xlarge">
                    <span class="add-on"><i class="icon-question-sign"></i></span>
                </div>
                <!--<p class="help-block">Supporting help text</p>-->
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="input01">Password</label>
            <div class="controls">
                <div class="input-append">
                    <input id="password" name="password" type="password" title="Tets info k nejakemu inputu" class="input-xlarge">
                    <span class="add-on"><i class="icon-question-sign"></i></span>
                </div>
            </div>
        </div>
    </fieldset>
    <div class="buttons">
        <a class="btn btn-primary btn-large left">Login</a>
        <a class="btn btn-primary btn-large right">Cancel</a>
    </div>
</div>