<?php $form->prepare(); ?>
<div id="content" class="content">
    <div class="right"><span><a href="<?php echo $this->url('register'); ?>"><?php echo $this->translate('Registration'); ?></a></span></div>
    <h1><?php echo $this->translate('No-Money'); ?></h1>
    <?php echo $this->form()->openTag($this->form) . PHP_EOL; ?>
    <fieldset>
        <legend><?php echo $this->translate('Login Form'); ?></legend>
        <div class="control-group">
            <?php echo $this->formLabel($this->form->get('email')) . PHP_EOL; ?>
            <div class="controls">
                <div class="input-append">
                    <?php echo $this->formElement($this->form->get('email')) . PHP_EOL; ?>
                    <span class="add-on"><i class="icon-question-sign"></i></span>
                </div>
                <p class="help-block"><?php echo $this->formElementErrors($this->form->get('email')) . PHP_EOL; ?></p>
            </div>
        </div>
        <div class="control-group">
            <?php echo $this->formLabel($this->form->get('password')) . PHP_EOL; ?>
            <div class="controls">
                <div class="input-append">
                    <?php echo $this->formElement($this->form->get('password')) . PHP_EOL; ?>
                    <span class="add-on"><i class="icon-question-sign"></i></span>
                    <p class="help-block"><?php echo $this->formElementErrors($this->form->get('password')) . PHP_EOL; ?></p>
                </div>
                <div><span><a href="<?php echo $this->url('lostpassword'); ?>"><?php echo $this->translate('Did you forget your password ?'); ?></a></span></div>
            </div>
            <?php if ($this->form->has('captcha')): ?>
                <div>
                    <?php echo $this->formElement($this->form->get('captcha')) . PHP_EOL; ?>
                    <?php echo $this->formElementErrors($this->form->get('captcha')) . PHP_EOL; ?>
                </div>
            <?php endif; ?>
            <div>
                <?php echo $this->formHidden($this->form->get('csrf')) . PHP_EOL; ?>
                <?php echo $this->formElementErrors($this->form->get('csrf')) . PHP_EOL; ?>
            </div>
    </fieldset>
    <div class="buttons">
        <?php echo $this->formElement($this->form->get('submit')); ?>
        <?php echo $this->formElement($this->form->get('reset')); ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    <div>
        <?php echo (!empty($this->message)) ? $this->translate($this->message) : ''; ?>
    </div>
</div>