<?php $form->prepare(); ?>
<div id="content" class="content">
    <div class="right"><span><a href="<?php echo $this->url('login'); ?>"><?php echo $this->translate('Login'); ?></a></span></div>
    <h1><?php echo $this->translate('No-Money'); ?></h1>
    <?php echo $this->form()->openTag($this->form) . PHP_EOL; ?>
    <fieldset>
        <legend><?php echo $this->translate('Lost password form'); ?></legend>
        <div class="control-group">
            <?php echo $this->formLabel($this->form->get('email')) . PHP_EOL; ?>
            <div class="controls">
                <div class="input-append">
                    <?php echo $this->formElement($this->form->get('email')) . PHP_EOL; ?>
                    <span class="add-on"><i class="icon-question-sign"></i></span>
                </div>
                <p class="help-block"><?php echo $this->formElementErrors($this->form->get('email')) . PHP_EOL; ?></p>
            </div>
        </div>
    </fieldset>
    <div class="buttons">
        <?php echo $this->formElement($this->form->get('submit')); ?>
        <?php echo $this->formElement($this->form->get('reset')); ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    <div>
        <?php echo $this->translate($this->message); ?>
    </div>
</div>