<?php $form->prepare(); ?>
<div id="content" class="content">
    <div class="right"><span><a href="<?php echo $this->url('login'); ?>"><?php echo $this->translate('Login'); ?></a></span></div>
    <h1><?php echo $this->translate('No-Money'); ?></h1>
    <?php echo $this->form()->openTag($this->form) . PHP_EOL; ?>
    <fieldset>
        <legend><?php echo $this->translate('Registration form'); ?></legend>
        <div class="control-group">
            <fieldset>
                <legend><?php echo $this->translate('Login info'); ?></legend>
                <div>
                    <?php echo $this->formLabel($this->form->get('email')) . PHP_EOL; ?>
                    <?php echo $this->formElement($this->form->get('email')) . PHP_EOL; ?>
                    <?php echo $this->formElementErrors($this->form->get('email')) . PHP_EOL; ?>
                </div>
                <div>
                    <?php echo $this->formLabel($this->form->get('password')) . PHP_EOL; ?>
                    <?php echo $this->formElement($this->form->get('password')) . PHP_EOL; ?>
                    <?php echo $this->formElementErrors($this->form->get('password')) . PHP_EOL; ?>
                </div>
                <div>
                    <?php echo $this->formLabel($this->form->get('passwordtwo')) . PHP_EOL; ?>
                    <?php echo $this->formElement($this->form->get('passwordtwo')) . PHP_EOL; ?>
                    <?php echo $this->formElementErrors($this->form->get('passwordtwo')) . PHP_EOL; ?>
                </div>
            </fieldset>

            <fieldset>
                <legend><?php echo $this->translate('Personal info'); ?></legend>
                <div>
                    <?php echo $this->formLabel($this->form->get('name')) . PHP_EOL; ?>
                    <?php echo $this->formElement($this->form->get('name')) . PHP_EOL; ?>
                    <?php echo $this->formElementErrors($this->form->get('name')) . PHP_EOL; ?>
                </div>
                <div>
                    <?php echo $this->formLabel($this->form->get('lastName')) . PHP_EOL; ?>
                    <?php echo $this->formElement($this->form->get('lastName')) . PHP_EOL; ?>
                    <?php echo $this->formElementErrors($this->form->get('lastName')) . PHP_EOL; ?>
                </div>
            </fieldset>
        </div>
        <?php if ($this->form->has('captcha')): ?>
            <div>
                <?php echo $this->formElement($this->form->get('captcha')) . PHP_EOL; ?>
                <?php echo $this->formElementErrors($this->form->get('captcha')) . PHP_EOL; ?>
            </div>
        <?php endif; ?>
        <?php echo $this->formHidden($this->form->get('csrf')) . PHP_EOL; ?>
        <?php echo $this->formElementErrors($this->form->get('csrf')) . PHP_EOL; ?>
    </fieldset>
    <div class="buttons">
        <?php echo $this->formElement($this->form->get('submit')); ?>
        <?php echo $this->formElement($this->form->get('reset')); ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    <div>
        <?php echo (!empty($this->message)) ? $this->translate($this->message) : ''; ?>
    </div>
</div>