<?php $form->prepare(); ?>
<div id="content" class="content">
    <div class="right"><span><a href="<?php echo $this->url('login'); ?>"><?php echo $this->translate('Login'); ?></a></span></div>
    <h1><?php echo $this->translate('No-Money'); ?></h1>
    <?php echo $this->form()->openTag($this->form) . PHP_EOL; ?>
    <fieldset>
        <legend><?php echo $this->translate('Registration form'); ?></legend>
        <div class="control-group">
            <?php echo $this->formCollection($form->get('loginInfo')); ?>
            <?php echo $this->formCollection($form->get('personInfo')); ?>
        </div>
    </fieldset>
    <div class="buttons">
        <?php echo $this->formElement($this->form->get('submit')); ?>
        <?php echo $this->formElement($this->form->get('reset')); ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    <div>
        <?php echo $this->message; ?>
    </div>
</div>