<div id="content" class="content">
    <div class="right"><span><a href="<?php echo $this->url('login'); ?>"><?php echo $this->translate('Login'); ?></a></span></div>
    <h1><?php echo $this->translate('No-Money'); ?></h1>
    <h3><?php echo $this->translate('Retrieve password'); ?></h3>
    
    <div id="retrieve">
        <div><strong><?php echo $this->translate('Key'); ?>:</strong> <span><?php echo $this->id; ?></span></div>
    </div>
    
    <div>
        <?php echo $this->translate('Your new password was send to email. Please change this password.'); ?>
    </div>
    
    <div>
        <?php echo $this->translate('Your new password is:') . $this->message; ?>
    </div>
</div>