<div class="content">
    <h1><?php echo $this->translate('Calculator'); ?></h1>
</div>

<div class="content" id="showMoney">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th><?php echo $this->translate('#'); ?></th>
                <th><?php echo $this->translate('Name'); ?></th>
                <th><?php echo $this->translate('Value'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->money as $k => $row): ?>
            <tr>
                <td><?php echo $k + 1; ?></td>
                <td><?php echo $row->categName; ?></td>
                <td><?php echo $row->sumary; ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>