<?php $this->subject = $this->translate('Lost Password'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <title></title>
    </head>
    <body>
        <h1><?php echo $this->translate('Recover password'); ?></h1>
        <p><?php echo $this->translate('To recover password use this link'); ?></p>
        <p><?php echo $this->translate('Link'); ?>: <a href="<?php echo $this->link; ?>"><?php echo $this->link; ?></a></p>
        <br />
        <p><?php echo $this->translate('If you dont want to reset your password, please ignore this email.'); ?></p>
    </body>
</html>