<?php $this->subject = $this->translate('Welcome'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <title></title>
    </head>
    <body>
        <h1><?php echo $this->translate('No-money'); ?></h1>
        <h3><?php echo $this->translate('Welcome to our service.'); ?></h3>
        <p>This is only developers version.</p>
    </body>
</html>