<?php echo $this->doctype(); ?>
<html lang="cs" class="no-js">
    <head>
        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        
        <meta charset=utf-8>
        <?php echo $this->headTitle('Money')->setSeparator(' - ')->setAutoEscape(false); ?>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <link href="<?php echo $this->public('/layout/jquery-ui-1.8.17.custom.css'); ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->public('/layout/bootstrap/bootstrap.min.css'); ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->public('/layout/datepicker/css/datepicker.css'); ?>" rel="stylesheet" type="text/css"/>

        <link href="<?php echo $this->public('/layout/layout.css?v=1'); ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->public('/layout/content.css?v=2'); ?>" rel="stylesheet" type="text/css"/>
        <!--[if IE]>
            <link href="<?php echo $this->public('/layout/layoutIE.css'); ?>" rel="stylesheet" type="text/css"/>
        <![endif]-->
        <!--[if IE 7]>
            <link href="<?php echo $this->public('/layout/layoutIE7.css'); ?>" rel="stylesheet" type="text/css"/>
        <![endif]-->
        <!--[if IE 8]>
            <link href="<?php echo $this->public('/layout/layoutIE8.css'); ?>" rel="stylesheet" type="text/css"/>
        <![endif]-->
        <!--[if IE 9]>
            <link href="<?php echo $this->public('/layout/layoutIE9.css'); ?>" rel="stylesheet" type="text/css"/>
        <![endif]-->
        <link href="<?php echo $this->public('/layout/hacks.css'); ?>" rel="stylesheet" type="text/css"/>

        <script type="text/javascript" src="<?php echo $this->public('/layout/js/modernizr.custom.33887.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/jquery-1.7.1.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/jquery.cookie.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/jquery-ui-1.8.17.custom.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/jquery-ui-timepicker-addon.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/jquery.color.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/bootstrap.min.js'); ?>"></script>

        <script type="text/javascript" src="<?php echo $this->public('/layout/datepicker/js/datepicker.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/datepicker/js/eye.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/datepicker/js/utils.js'); ?>"></script>
        
        <script type="text/javascript">
            var baseUrl = '<?php echo $this->url('home'); ?>';
        </script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/translate.js'); ?>"></script>
        
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/forms.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/application.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/charts.js'); ?>"></script>
        
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-35562652-1']);
          _gaq.push(['_setDomainName', 'no-money.cz']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script>
    </head>
    <body>
        <!--   IE not suported     -->
        <div id="ieh">
            <p>Omlouváme se ale váš prohlížeč již <span>není podporován.</span> Proto můžete mít potíže se zobrazením tohoto webu. Update si můžete stáhnout na této <a href="http://windows.microsoft.com/cs-CZ/internet-explorer/products/ie/home">stránce.</a></p>
        </div>

        <div id="blocks">
            <div class="w30" id="leftBlockHead">
                <div class="padding">
                    <div class="content" id="head">
                        <a href="<?php echo $this->url('home'); ?>"><?php echo $this->translate('No-Money'); ?></a>
                    </div>
                </div>
            </div>
            <div class="w70" id="rightBlockHead">
                <div class="padding">
                    <div class="content" id="headMenu">
                        <div class="subnav">
                            <?php echo $this->navigation('Navigation')->menu()->setPartial('navigation/main.phtml'); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cleaner"></div>

            <div class="w30" id="leftBlock">
                <div class="padding">
                    <div id="sidebar">
                        <?php echo $this->render('custom/sideMenu.phtml'); ?>
                    </div>
                </div>
            </div>

            <div class="w70" id="rightBlock">
                <div class="padding">
                    <div id="inner">
                        <div id="messages">
                            <?php echo $this->render('custom/messages.phtml'); ?>
                        </div>
                        <?php echo $this->render('custom/addMoney.phtml'); ?>
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="cleaner"></div>
    </body>	
</html>