<?php echo $this->doctype(); ?>
<html lang="cs" class="no-js">
    <head>
        <meta charset=utf-8>
        <?php echo $this->headTitle('Money')->setSeparator(' - ')->setAutoEscape(false); ?>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        
        <link href="<?php echo $this->public('/layout/jquery-ui-1.8.17.custom.css'); ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->public('/layout/bootstrap/bootstrap.min.css'); ?>" rel="stylesheet" type="text/css"/>

        <link href="<?php echo $this->public('/layout/layout.css?v=1'); ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->public('/layout/content.css?v=1'); ?>" rel="stylesheet" type="text/css"/>
        <!--[if IE]>
            <link href="<?php echo $this->public('/layout/layoutIE.css'); ?>" rel="stylesheet" type="text/css"/>
        <![endif]-->
        <!--[if IE 7]>
            <link href="<?php echo $this->public('/layout/layoutIE7.css'); ?>" rel="stylesheet" type="text/css"/>
        <![endif]-->
        <!--[if IE 8]>
            <link href="<?php echo $this->public('/layout/layoutIE8.css'); ?>" rel="stylesheet" type="text/css"/>
        <![endif]-->
        <!--[if IE 9]>
            <link href="<?php echo $this->public('/layout/layoutIE9.css'); ?>" rel="stylesheet" type="text/css"/>
        <![endif]-->
        <link href="<?php echo $this->public('/layout/hacks.css?v=1'); ?>" rel="stylesheet" type="text/css"/>

        <script type="text/javascript" src="<?php echo $this->public('/layout/js/modernizr.custom.33887.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/jquery-1.7.1.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/jquery.cookie.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/jquery-ui-1.8.17.custom.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/jquery-ui-timepicker-addon.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/jquery.color.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/bootstrap.min.js'); ?>"></script>


        <script type="text/javascript" src="<?php echo $this->public('/layout/js/application.js'); ?>"></script>
    </head>
    <body>
        <!--   IE not suported     -->
        <div id="ieh">
            <p>Omlouváme se ale váš prohlížeč již <span>není podporován.</span> Proto můžete mít potíže se zobrazením tohoto webu. Update si můžete stáhnout na této <a href="http://windows.microsoft.com/cs-CZ/internet-explorer/products/ie/home">stránce.</a></p>
        </div>

        <div id="blocks">
            <div class="w30" id="leftBlockHead">
                <div class="padding">
                    <div class="content" id="head">
                        Money
                    </div>
                </div>
            </div>
            <div class="w70" id="rightBlockHead">
                <div class="padding">
                    <div class="content" id="headMenu">
                        <div class="subnav">
                            <ul class="nav nav-pills">
                                <li class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Buttons <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#buttonGroups">Button groups</a></li>
                                        <li><a href="#buttonDropdowns">Button dropdowns</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Navigation <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#navs">Nav, tabs, pills</a></li>
                                        <li><a href="#navbar">Navbar</a></li>
                                        <li><a href="#breadcrumbs">Breadcrumbs</a></li>
                                        <li><a href="#pagination">Pagination</a></li>
                                    </ul>
                                </li>
                                <li><a href="#labels">Labels</a></li>
                                <li><a href="#badges">Badges</a></li>
                                <li><a href="#typography">Typography</a></li>
                                <li><a href="#thumbnails">Thumbnails</a></li>
                                <li><a href="#alerts">Alerts</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cleaner"></div>

            <div class="w30" id="leftBlock">
                <div class="padding">
                    <div id="sidebar">
                        <div class="content">
                            <ul class="nav nav-list">
                                <li class="nav-header">List of Modules</li>
                                <li class="active"><a href="#"><i class="icon-file icon-white"></i> Articles</a></li>
                                <li><a href="#"><i class="icon-file"></i> Pages</a></li>
                                <li><a href="#"><i class="icon-file"></i> Galery</a></li>
                                <li><a href="#"><i class="icon-file"></i> Tags</a></li>
                                <li><a href="#"><i class="icon-file"></i> Comments</a></li>
                                <li class="divider"></li>
                                <li class="nav-header">Others</li>
                                <li><a href="#"><i class="icon-file"></i> Settings</a></li>
                            </ul>
                        </div>
                        <div class="content attach">
                            Some content
                        </div>
                        <div class="content">

                            <ul class="nav nav-list">
                                <li class="nav-header">Others</li>
                                <li><a href="#"><i class="icon-file"></i> Settings</a></li>
                                <li><a href="#"><i class="icon-file"></i> Other Settings</a></li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>

            <div class="w70" id="rightBlock">
                <div class="padding">
                    <div id="inner">
                        <div id="messages">
                            <div class="content alert alert-success alert-block">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                <h4>Warning!</h4>
                                Best check yo self, you're not...
                            </div>
                            <div class="content alert alert-warning alert-block">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                <h4>Warning!</h4>
                                Best check yo self, you're not...
                            </div>
                            <div class="content alert alert-error alert-block">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                <h4>Warning!</h4>
                                Best check yo self, you're not...
                            </div>
                        </div>
                        
                        <?php echo $this->content; ?>

                    </div>
                </div>
            </div>
        </div>
        <div class="cleaner"></div>

        <div id="footer">
            Money 2012
        </div>
    </body>	
</html>