<!DOCTYPE html>
<html lang="cs" class="no-js">
    <head>
        <meta charset=utf-8>
        <?php echo $this->headTitle('Money')->setSeparator(' - ')->setAutoEscape(false); ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        
        <link href="<?php echo $this->public('/layout/mobile/ratchet.css'); ?>" rel="stylesheet" type="text/css"/>

        <script type="text/javascript" src="<?php echo $this->public('/layout/js/modernizr.custom.33887.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/jquery-1.7.1.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/jquery.cookie.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->public('/layout/mobile/ratchet.js'); ?>"></script>
       
        <script type="text/javascript" src="<?php echo $this->public('/layout/js/translate.js'); ?>"></script>
        
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-35562652-1']);
          _gaq.push(['_setDomainName', 'no-money.cz']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script>
    </head>
    <body>
        <?php echo $this->content; ?>
    </body>	
</html>