<!--<div class="content alert alert-success alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Warning!</h4>
    Best check yo self, you're not...
</div>
<div class="content alert alert-warning alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Warning!</h4>
    Best check yo self, you're not...
</div>
<div class="content alert alert-error alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Warning!</h4>
    Best check yo self, you're not...
</div>-->
<?php foreach ($this->flashMessanger()->getMessages() as $message): ?>
    <?php if (is_array($message)): ?>
<div class="content alert alert-<?php echo strtolower($message['type']); ?> alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4><?php echo $this->translate((isset($message['title']) ? $message['title'] : $message['type'])); ?></h4>
            <?php echo $this->translate($message['message']); ?>
        </div>
    <?php else: ?>
        <div class="content alert alert-success alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4><?php echo $this->translate('Message'); ?></h4>
            <?php echo $this->translate($message); ?>
        </div>
    <?php endif; ?>
<?php endforeach; ?>
