<!--<div class="content alert alert-success alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Warning!</h4>
    Best check yo self, you're not...
</div>
<div class="content alert alert-warning alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Warning!</h4>
    Best check yo self, you're not...
</div>
<div class="content alert alert-error alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Warning!</h4>
    Best check yo self, you're not...
</div>-->