<div class="content">
    <div id="widgetField">
        <div></div>
        <a href="#">Select date range</a>
    </div>
    <div id="widgetCalendar">
    </div>
</div>
<!--<div class="content">
    <ul class="nav nav-list">
        <li class="nav-header">List of Modules</li>
        <li class="active"><a href="#"><i class="icon-file icon-white"></i> Articles</a></li>
        <li><a href="#"><i class="icon-file"></i> Pages</a></li>
        <li><a href="#"><i class="icon-file"></i> Galery</a></li>
        <li><a href="#"><i class="icon-file"></i> Tags</a></li>
        <li><a href="#"><i class="icon-file"></i> Comments</a></li>
        <li class="divider"></li>
        <li class="nav-header">Others</li>
        <li><a href="#"><i class="icon-file"></i> Settings</a></li>
    </ul>
</div>
<div class="content attach">

    <ul class="nav nav-list">
        <li class="nav-header">Others</li>
        <li><a href="#"><i class="icon-file"></i> Settings</a></li>
        <li><a href="#"><i class="icon-file"></i> Other Settings</a></li>
    </ul>

</div>-->