<li><a href="<?php echo $this->url('application/default', array('controller' => 'category', 'action' => 'create')); ?>"><?php echo $this->translate('Create category'); ?></a></li>
<li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'history')); ?>"><?php echo $this->translate('History'); ?></a></li>

<li class="divider-vertical"></li>

<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><?php echo $this->user(); ?> <b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li><a href="<?php echo $this->url('profil'); ?>"><i class="icon-user"></i> <?php echo $this->translate('Profil'); ?></a></li>
        <li><a href="<?php echo $this->url('settings'); ?>"><i class="icon-wrench"></i> <?php echo $this->translate('Settings'); ?></a></li>
        <li class="divider"></li>
        <li><a href="<?php echo $this->url('logout'); ?>"><i class="icon-off"></i> <?php echo $this->translate('Logout'); ?></a></li>
    </ul>
</li>