<div class="content">
    <h1><?php echo $this->translate('Your money'); ?></h1>
</div>

<div class="content">
    <div id="chart_spending"></div>
</div>

<div class="content">
    <div id="chart_spending_category"></div>
</div>

<div class="content" id="showMoney">
    <?php foreach($this->moneys as $money): ?>
    <div class="well money <?php echo ($money->value < 0) ? 'less' : 'more'; ?>">
        <h4><?php echo $money->title; ?></h4>
        <div class="date"><?php echo date('d.m.Y', strtotime($money->date)); ?></div>
        <div class="cleaner"></div>
        <div class="category"><?php echo $money->categName ?> <span><?php echo $money->subcategName ?></span></div>
        <div class="value <?php echo ($money->value < 0) ? 'less' : 'more'; ?>"><?php echo $money->value; ?></div>
        <div class="delete">
            <a class="confirm" href="<?php echo $this->url('money/delete', array('id' => $money->id)); ?>">
                <?php echo $this->translate('Delete'); ?>
            </a>
        </div>
    </div>
    <?php endforeach; ?>
</div>