<div class="content">
    <h1><?php echo $this->translate('Your money'); ?></h1>
</div>

<div class="content">
    <div id="chart_summary"></div>
</div>

<div class="content">
    <div id="chart_spending"></div>
</div>

<div class="content">
    <div id="chart_spending_category"></div>
</div>

<div class="content" id="showMoney">
    <?php foreach ($this->moneys as $money): ?>
        <?php echo $this->render('custom/money.phtml', array('money' => $money)); ?>
    <?php endforeach; ?>
</div>